- name: Ssh
  hosts: all

  tasks:
  - name: Copy sshd config
    copy:
      src: "./sshd_config"
      dest: "/etc/ssh/sshd_config"
  - name: Enable sshd 
    service: 
      name: sshd
      state: started
      enabled: yes
  - name: Restart service
    service:
      name: sshd
      state: restarted
