- name: create users
  hosts: all
  
  tasks: 
    - name: create users 
      user: 
        name: Webdeveloper
        password: "$1$salt$4at6qU1uQeVQlp1jKPGCt/"
        state: present
    - name: create .ssh 
      file:
        state: directory
        path: "/home/Webdeveloper/.ssh"       
    - name: copy pub key
      copy: 
        src: ./id_ssh.pub
        dest: /home/Webdeveloper/.ssh/authorized_keys


    - name: create users 
      user: 
        name: Devopsengineer
        password: "$1$salt$fVQ8jpmkFUvIWFxeHvGox0"
        state: present
    - name: create .ssh 
      file:
        state: directory
        path: "/home/Devopsengineer/.ssh"       
    - name: copy pub key
      copy: 
        src: ./id_ssh.pub
        dest: /home/Devopsengineer/.ssh/authorized_keys

    - name: create users 
      user: 
        name: Projectmanager
        password: "$1$salt$ZEdPzSV4gyvzlY5OtmskX1"
        state: present
    - name: create .ssh 
      file:
        state: directory
        path: "/home/Projectmanager/.ssh"       
    - name: copy pub key
      copy: 
        src: ./id_ssh.pub
        dest: /home/Projectmanager/.ssh/authorized_keys


      #      ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCovvBkeLIDsvbCyQsMWtPWVgGVKcwAqRONiBJ9JyrVCQbruyMPutatjSlhNpYXKLlP4BXHrGrmAVqeI155li1fkNP5Il7viHRE0HvA3M2extNGDDCiX5f5OlIeT9p/D9OHvWWozLjN2NAGEW24feuzKPZb6Kyv2W3yHbiIU3wt8v50VAIA2+PAfElHp1jplGHQLmYuT6Cc26Pn3WYXZ8t8oU77T6Ki5qDG5V5DVZI3Ym5gqqXXtJYzET9piJvO6qiIcgljtOGlUH9H9QNLEbuF+RKIhL3pFAnF8S79Km2A3j9KFZw6prDR6/VeMffMrNSZLeYztzDGEzm35uz5q6j+qrKsuA4SfpbSOcBwaariOoKpb6JfogoJRgCqxR5O1AKR/Oqhdk6JOlKJk+tIXFmOczH7da/W93f8KGGve4iHRvz/e3vYA7exXIVkD8mc/VmIoT1kqh/uNGia/adnyCgvMpL8JXLJgY2DThpjHslUr0RTEpQJTLTka3D43YV37kM=

